// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using platterr_api.Data;

namespace platterr_api.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211017144108_ScheduledNotifications")]
    partial class ScheduledNotifications
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("platterr_api.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerLastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Delivery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Paid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("platterr_api.Entities.Platter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platters");
                });

            modelBuilder.Entity("platterr_api.Entities.PlatterFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlatterId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlatterId");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("platterr_api.Entities.PlatterRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlatterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PlatterId");

                    b.ToTable("PlatterRequests");
                });

            modelBuilder.Entity("platterr_api.Entities.PlatterFormat", b =>
                {
                    b.HasOne("platterr_api.Entities.Platter", "Platter")
                        .WithMany("Formats")
                        .HasForeignKey("PlatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platter");
                });

            modelBuilder.Entity("platterr_api.Entities.PlatterRequest", b =>
                {
                    b.HasOne("platterr_api.Entities.PlatterFormat", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId");

                    b.HasOne("platterr_api.Entities.Order", "Order")
                        .WithMany("Platters")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("platterr_api.Entities.Platter", "Platter")
                        .WithMany()
                        .HasForeignKey("PlatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Format");

                    b.Navigation("Order");

                    b.Navigation("Platter");
                });

            modelBuilder.Entity("platterr_api.Entities.Order", b =>
                {
                    b.Navigation("Platters");
                });

            modelBuilder.Entity("platterr_api.Entities.Platter", b =>
                {
                    b.Navigation("Formats");
                });
#pragma warning restore 612, 618
        }
    }
}
